### ISSUE TITLE
Weapons from ArcCw do not deal damage while GWZ HUD is enabled.

### ISSUE THREAD

**Issue by ShadowWolf90** [URAKOLOUY5/GWZ-Hud#15]
GWZ HUD causes any ArcCW weapon to do not deal any damage.

**Comment by URAKOLOUY5** [comment]
This is still happens? I can't reproduce this on my side

**Comment by ShadowWolf90** [comment]
I will check it tomorrow and give you answer once i reinstall HUD

**Comment by ShadowWolf90** [comment]
> This is still happens? I can't reproduce this on my side

Addon checked.
ArcCW and GWZ HUD does not conflict for now.
Damage done by any weapon based on ArcCW are applied correctly.
