### ISSUE TITLE
Killfeed/Team HUD support for Zeta Players (Workshop Addon)

### ISSUE THREAD

**Issue by ShadowWolf90** [URAKOLOUY5/GWZ-Hud#17]
Support for addon: https://steamcommunity.com/sharedfiles/filedetails/?id=2773405248

**Comment by URAKOLOUY5** [comment]
Killfeed will be done later, team support only for showing friend's position (not list them in "teammates" list).

**Comment by ShadowWolf90** [comment]
Okey, however there's addon that adds artificial players, and would be nice if HUD will be compatible with them, since they have nicknames and most of huds/killfeeds/team managment addons falsely show them or ignore

**Comment by URAKOLOUY5** [comment]
Tried to add in next update but didn't, so i'll do this later.

**Comment by ShadowWolf90** [comment]
Understood

**Comment by URAKOLOUY5** [comment]
Added in `30.08.22` update, thanks for suggestion!

**Comment by ShadowWolf90** [comment]
Console throws error code on Zeta Death:
[GWZ - COD:Warzone Hud] lua/autorun/gwz_hud/world_teamicon.lua:575: Tried to use a NULL entity!
  1. LookupBone - [C]:-1
   2. func - lua/autorun/gwz_hud/world_teamicon.lua:575
    3. unknown - lua/includes/extensions/net.lua:33
