### ISSUE TITLE
Support for Zeta Players can be buggy

### ISSUE THREAD

**Issue by URAKOLOUY5** [URAKOLOUY5/GWZ-Hud#20]

**Comment by ShadowWolf90** [comment]
Bug found

Console give this message when Zeta Player dies

Code:
`
[GWZ - COD:Warzone Hud] lua/autorun/gwz_hud/world_teamicon.lua:575: Tried to use a NULL entity!
  1. LookupBone - [C]:-1
   2. func - lua/autorun/gwz_hud/world_teamicon.lua:575
    3. unknown - lua/includes/extensions/net.lua:33
`

**Comment by ShadowWolf90** [comment]
Suggestion: Zeta Player Position mark could show offscreen

**Comment by URAKOLOUY5** [comment]
> Suggestion: Zeta Player Position mark could show offscreen

I've been wanting to do that for a long time, since this is feature in MW19/Warzone.

> Bug found
> ...

This is bug for players too, so yeah, I will try to find a solution so that this error does not appear, because it does not breaks the code, but it must be fixed.

**Comment by ShadowWolf90** [comment]
> PS: Probably i fixed this, due latest in-dev refactor (for performance)

On steam version still error exists.

**Comment by ShadowWolf90** [comment]
Bug found.

If you play with normal human players and they go far away, their nick in overhead change from: *player nick* to Zeta Player.
